name: automation_latest_tag_action_1749623677-8wkbb3

on:
  schedule:
  - cron: '31 11 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@latest
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN}}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
