name: automation_branch_injection_workflow_1749623677-8wkbb3

on: workflow_dispatch

jobs:
  insecure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print GitHub Ref
        run: |
            echo "GitHub Ref: ${{ github.ref }}"

      - name: Branch Path Traversal - Dangerous file operation
        run: "rm -rf /some/path/${{ github.head_ref }}/../important_file"

      - name: Branch Script Execution - Executing a script from branch name
        run: "/${{ github.ref }}/malicious.sh"

      - name: Branch String Manipulation - Dangerous string usage
        run: "echo '${{ github.ref }}' || eval 'rm -rf /'"

      - name: Direct Branch Usage Without Validation - Direct use of branch reference
        run: "git checkout ${{ github.head_ref }}"
