name: automation_unsecure_cmd_workflow_1748347956-k402tq

on: workflow_dispatch

jobs:
  insecure-job:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run an insecure command
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        run: |
          echo "This is an insecure workflow!"
          echo "::set-env name=MY_SECRET::unsafe_value"  # Deprecated and dangerous
